### ISSUE TITLE
como se escriben los modos?

### ISSUE THREAD

**Issue by mdforti** [rodrigolx31/finel3d#2]
como estoy al pedo me puse a jugar con tu programa. cuando ejecuto por ejemplo con smple_bar1 , veo que guarda solo algun modo que no es el primero. como selecciono el modo a escribir ?
Debería haber al menos alguna indicacion de cual es el modo escrito

**Comment by mdforti** [comment]
hice un pull request con la modificacion

**Comment by rodrigolx31** [comment]
en finel.py en el apartado de modos normales. En la línea 295 te define qué modo normal está graficando. Se podría hacer un input de eso.
